# Generated by Django 2.0.6 on 2018-06-10 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefixo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LotacaoCircular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected', models.DateField()),
                ('lotacao', models.IntegerField()),
                ('circular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotacoes', to='app.Circular')),
            ],
        ),
        migrations.CreateModel(
            name='LotacaoPonto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected', models.DateField()),
                ('lotacao', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ponto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='lotacaoponto',
            name='circular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotacoes', to='app.Ponto'),
        ),
    ]
