# Generated by Django 2.0.6 on 2018-06-10 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponto',
            name='lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ponto',
            name='lon',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
