# Generated by Django 2.0.6 on 2018-06-10 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_ponto_ultimo_circular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponto',
            name='ultimo_circular',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ultimo_ponto', to='app.Circular'),
        ),
    ]
