# Generated by Django 2.0.6 on 2018-06-10 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180610_0801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lotacaocircular',
            options={'ordering': ['-collected']},
        ),
    ]
